sudo: required
services: 
  - docker

before_install:
  - docker build -t rybalka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rybalka/react-test npm run test

after_success:
  - docker build -t rybalka/multi-client ./client
  - docker build -t rybalka/multi-nginx ./nginx
  - docker build -t rybalka/multi-server ./server
  - docker build -t rybalka/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 

  - docker push rybalka/multi-client  
  - docker push rybalka/multi-nginx  
  - docker push rybalka/multi-server  
  - docker push rybalka/multi-worker  

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "muli-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-972680654808"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
